services:
  guardian-service:
    build:
      context: .
      dockerfile: guardian-service/Dockerfile
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: test
    healthcheck:
      test: ['CMD-SHELL', 'curl -f  http://localhost:3001/health || exit 1']
      interval: 5s
      timeout: 5s
      retries: 10

  ui:
    image: nginx:alpine
    ports:
      - '3000:80'
    volumes:
      - ./tests-ui/mock-ui:/usr/share/nginx/html:ro
