import * as dotenv from 'dotenv';
import fs from 'fs';
import path from 'path';
import process from 'process';
import { fileURLToPath } from 'url';
dotenv.config();

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const reportsDir = path.resolve(__dirname, '..', 'reports');

const getJSON = (file) => {
  const fullPath = path.join(reportsDir, file);
  return fs.existsSync(fullPath)
    ? JSON.parse(fs.readFileSync(fullPath, 'utf-8'))
    : null;
};

//Guardian Service (Jest Coverage)
const getGuardianReport = () => {
  const data = getJSON('unit-coverage/coverage-summary.json');
  if (!data || !data.total || !data.total.lines)
    return '| **Guardian Service** | N/A | Missing |';

  const pct = data.total.lines.pct;

  if (pct === 'Unknown' || pct === undefined)
    return '| **Guardian Service** | 0% | ❌ No Data |';

  const numericPct = parseFloat(pct);
  const status = numericPct >= 100 ? '✅ 100%' : `⚠️${numericPct}%`;
  return `| **Guardian Service** | ${numericPct}% Line Coverage | ${status} |`;
};

//UI Tests (Playwright)
const getUIReport = () => {
  const data = getJSON('ui-results.json');
  if (!data) return '| **UI Tests** | N/A | Missing |';

  const stats = data.stats;
  const errors = data.errors || [];

  if (errors.length > 0 || (stats.expected === 0 && stats.unexpected === 0)) {
    const errorMsg = errors[0]?.message || 'No tests found';
    return `| **UI Tests** | 0 Passed |  Error: ${errorMsg} |`;
  }
  const status =
    stats.expected === 0 && stats.unexpected === 0 ? '✅ Pass' : '❌ Fail';
  return `| **UI Tests** | ${stats.expected} Passed | ${status} |`;
};

//Performance (k6)
const getPerfReport = () => {
  const data = getJSON('performance-summary.json');
  if (!data?.metrics) return '| **Performance** | N/A | Missing |';

  const m = data.metrics;
  const p95 = m.http_req_duration.values['p(95)']?.toFixed(2) || '0';
  const failRate = (m.http_req_failed?.values?.rate * 100).toFixed(2);

  const latencyOk = m.http_req_duration?.thresholds['p(95)<500']?.ok ?? false;
  const failRateOk = m.http_req_failed?.thresholds['rate<0.01']?.ok ?? false;

  const status = latencyOk && failRateOk ? '✅ Pass' : '❌ Fail';
  return `| **Performance** | P95: ${p95}ms / Errors: ${failRate}% | ${status} |`;
};

//Federated Model Drift
const getDriftReport = () => {
  const driftData = getJSON('drift-value.json');
  const testData = getJSON('federated-results.json');

  const value = driftData ? `${(driftData.drift * 100).toFixed(2)}%` : 'N/A';
  const status = testData?.numFailedTests === 0 ? 'Pass' : 'Fail';

  return `| **Model Drift** | Current Drift: ${value} | ${status} |`;
};

const getLintReport = () => {
  const data = getJSON('lint-results.json');
  if (!data) return '| **Code Quality** | N/A | Missing |';

  const errors = data.reduce((sum, file) => sum + file.errorCount, 0);
  const warnings = data.reduce((sum, file) => sum + file.warningCount, 0);

  const status = errors === 0 ? '✅ Clean' : `${errors} Errors`;
  const metrics = `${errors} Errors / ${warnings} Warnings`;

  return `| **Code Quality** |  ESLint ${metrics}  | ${status} |`;
};

const getFormatReport = () => {
  //formatting report
  return `| **Style & Format** | Prettier  | ✅ Consistent |`;
};

const getPactReport = () => {
  // Path to the contract file generated by Pact
  const pactFile = 'pact/pact-results.json';
  const data = getJSON(pactFile);

  if (!data || !data.results || !data.results.summary)
    return '| **Contract (Pact)** | N/A | ⚠️ Missing |';

  // Extract metadata from the pact file
  const summary = data.results.summary;
  const passed = summary.passed || 0;
  const failed = summary.failed || 0;
  const total = summary.tests || 0;

  const status = failed === 0 && passed > 0 ? '✅ Pass' : '❌ Fail';

  return `| **Contract (Pact)** | ${passed}/${total} Contracts | ${status} |`;
};

// 1. API Integration (Pass/Fail)
const getApiTestReport = () => {
  const data = getJSON('api/api-results.json');
  if (!data || !data.results || !data.results.summary)
    return '| **API Integration** | N/A | ⚠️ Missing |';

  // Standard Jest JSON fields
  const summary = data.results.summary;
  const passed = summary.passed || 0;
  const total = summary.tests || 0;
  const failed = summary.failed || 0;
  const status = failed === 0 && total > 0 ? '✅ Pass' : '❌ Fail';

  return `| **API Integration** | ${passed}/${total} Passed | ${status} |`;
};

//API Coverage (The % score)
const getApiCoverage = () => {
  const data = getJSON('api-coverage/coverage-summary.json');
  if (!data || !data.total || data.total.lines.pct === 'Unknown')
    return '| **API Coverage** | 0% | ❌ No Data |';

  const pct = data.total.lines.pct;
  const status = Number(pct) >= 95 ? '✅ >95%' : `⚠️ ${pct}%`;
  return `| **API Coverage** | ${pct}% Line Coverage | ${status} |`;
};

//BDD Metrics (Cucumber JSON)
const getBddReport = () => {
  const data = getJSON('bdd/bdd-results.json');
  if (!data || !Array.isArray(data))
    return '| **BDD (Cucumber)** | N/A | ⚠️ Missing |';

  let totalScenarios = 0;
  let passedScenarios = 0;

  data.forEach((feature) => {
    const scenarios = feature.elements.filter((el) => el.type === 'scenario');
    scenarios.forEach((scenario) => {
      totalScenarios++;
      // A scenario passes only if EVERY step is 'passed'
      const allStepsPassed = scenario.steps.every(
        (step) => step.result && step.result.status === 'passed',
      );
      if (allStepsPassed) passedScenarios++;
    });
  });

  const status =
    passedScenarios === totalScenarios && totalScenarios > 0
      ? '✅ Pass'
      : '❌ Fail';
  return `| **BDD (Cucumber)** | ${passedScenarios}/${totalScenarios} Scenarios | ${status} |`;
};

const summaryTable = `
# QA EXECUTION SUMMARY (OctaiPipe)

| Suite    |  Metrics| Status |
| :------- | :-------| :------|
${getGuardianReport()}
${getUIReport()}
${getPerfReport()}
${getDriftReport()}
${getLintReport()}
${getFormatReport()}
${getPactReport()}
${getApiTestReport()}
${getApiCoverage()}
${getBddReport()}

---
*Generated at ${new Date().toLocaleString()}*
`;

// Ensure reports directory exists before writing
if (!fs.existsSync(reportsDir)) fs.mkdirSync(reportsDir);

fs.writeFileSync(path.join(reportsDir, 'summary-report.md'), summaryTable);
console.log('Summary report generated');

if (process.env.GITHUB_STEP_SUMMARY) {
  fs.appendFileSync(process.env.GITHUB_STEP_SUMMARY, summaryTable);
}
